version: '3'

services:
  backend:
    build:
      context: ./etc/docker/backend
    volumes:
      - .:/app
    ports:
      - "8088:8088"
    links:
      - db

  db:
    image: mysql
    environment:
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8080:8080